
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.payexchange.ws.dao;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-16T13:24:19.361+08:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "EpinsUploadDAOService",
                      portName = "EpinsUploadDAOPort",
                      targetNamespace = "http://dao.ws.payexchange.com/",
                      wsdlLocation = "http://localhost:8080/EpinsUploadWS/services/EpinsUploadDAOPort?wsdl",
                      endpointInterface = "com.payexchange.ws.dao.EpinsUploadDAOSEI")
                      
public class EpinsUploadDAOSEIImpl implements EpinsUploadDAOSEI {

    private static final Logger LOG = Logger.getLogger(EpinsUploadDAOSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see com.payexchange.ws.dao.EpinsUploadDAOSEI#reqUpload(java.lang.String  arg0 ,)java.lang.String  arg1 ,)java.lang.String  arg2 ,)java.lang.String  arg3 ,)java.lang.String  arg4 ,)java.lang.String  arg5 ,)java.lang.String  arg6 ,)java.lang.String  arg7 ,)java.lang.String  arg8 ,)java.lang.String  arg9 ,)java.lang.String  arg10 ,)java.lang.String  arg11 )*
     */
    public com.payexchange.ws.dao.EpinsUploadResponse reqUpload(java.lang.String arg0,java.lang.String arg1,java.lang.String arg2,java.lang.String arg3,java.lang.String arg4,java.lang.String arg5,java.lang.String arg6,java.lang.String arg7,java.lang.String arg8,java.lang.String arg9,java.lang.String arg10,java.lang.String arg11) { 
        LOG.info("Executing operation reqUpload");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        System.out.println(arg4);
        System.out.println(arg5);
        System.out.println(arg6);
        System.out.println(arg7);
        System.out.println(arg8);
        System.out.println(arg9);
        System.out.println(arg10);
        System.out.println(arg11);
        try {
            com.payexchange.ws.dao.EpinsUploadResponse _return = new com.payexchange.ws.dao.EpinsUploadResponse();
            _return.setPassword("Password-1133988746");
            _return.setResultcode(-1339488136);
            _return.setTracenumber("Tracenumber-1829898220");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
