
package com.payexchange.ws.dao.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.7
 * Tue Nov 05 13:53:48 SGT 2013
 * Generated source version: 2.7.7
 */

@XmlRootElement(name = "reqUpload", namespace = "http://dao.ws.payexchange.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reqUpload", namespace = "http://dao.ws.payexchange.com/", propOrder = {"arg0", "arg1", "arg2", "arg3", "arg4", "arg5", "arg6", "arg7", "arg8", "arg9", "arg10", "arg11", "arg12"})

public class ReqUpload {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;
    @XmlElement(name = "arg2")
    private int arg2;
    @XmlElement(name = "arg3")
    private java.lang.String arg3;
    @XmlElement(name = "arg4")
    private java.lang.String arg4;
    @XmlElement(name = "arg5")
    private java.lang.String arg5;
    @XmlElement(name = "arg6")
    private java.lang.String arg6;
    @XmlElement(name = "arg7")
    private java.lang.String arg7;
    @XmlElement(name = "arg8")
    private java.lang.String arg8;
    @XmlElement(name = "arg9")
    private java.lang.String arg9;
    @XmlElement(name = "arg10")
    private java.lang.String arg10;
    @XmlElement(name = "arg11")
    private java.lang.String arg11;
    @XmlElement(name = "arg12")
    private java.lang.String arg12;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

    public int getArg2() {
        return this.arg2;
    }

    public void setArg2(int newArg2)  {
        this.arg2 = newArg2;
    }

    public java.lang.String getArg3() {
        return this.arg3;
    }

    public void setArg3(java.lang.String newArg3)  {
        this.arg3 = newArg3;
    }

    public java.lang.String getArg4() {
        return this.arg4;
    }

    public void setArg4(java.lang.String newArg4)  {
        this.arg4 = newArg4;
    }

    public java.lang.String getArg5() {
        return this.arg5;
    }

    public void setArg5(java.lang.String newArg5)  {
        this.arg5 = newArg5;
    }

    public java.lang.String getArg6() {
        return this.arg6;
    }

    public void setArg6(java.lang.String newArg6)  {
        this.arg6 = newArg6;
    }

    public java.lang.String getArg7() {
        return this.arg7;
    }

    public void setArg7(java.lang.String newArg7)  {
        this.arg7 = newArg7;
    }

    public java.lang.String getArg8() {
        return this.arg8;
    }

    public void setArg8(java.lang.String newArg8)  {
        this.arg8 = newArg8;
    }

    public java.lang.String getArg9() {
        return this.arg9;
    }

    public void setArg9(java.lang.String newArg9)  {
        this.arg9 = newArg9;
    }

    public java.lang.String getArg10() {
        return this.arg10;
    }

    public void setArg10(java.lang.String newArg10)  {
        this.arg10 = newArg10;
    }

    public java.lang.String getArg11() {
        return this.arg11;
    }

    public void setArg11(java.lang.String newArg11)  {
        this.arg11 = newArg11;
    }

    public java.lang.String getArg12() {
        return this.arg12;
    }

    public void setArg12(java.lang.String newArg12)  {
        this.arg12 = newArg12;
    }

}

